Organization.create!([
   {name: "Prophet LLC"}
])
User.create!([
  {email: "matt@gmail.com", first_name: "Matthew", last_name: "Dick", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 68, current_sign_in_at: "2016-03-26 22:04:15", last_sign_in_at: "2016-03-21 13:08:25", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@MatthewDick", avatar_file_name: "my_avatar.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 291331, avatar_updated_at: "2015-12-18 06:27:10", bio: "Badass programmer, all day every day ;)", title: "Software Engineer", type: nil, organization_id: 1},
  {email: "tony@gmail.com", first_name: "Tony", last_name: "Decino", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 25, current_sign_in_at: "2016-03-28 13:46:09", last_sign_in_at: "2016-03-18 05:56:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@TonyDecino", avatar_file_name: "tony_avatar.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 105745, avatar_updated_at: "2016-03-28 14:47:35", bio: "Tony D: Comp Masta", title: "Software Engineer", type: nil, organization_id: 1},
  {email: "user1@gmail.com", first_name: "User", last_name: "One", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2016-03-18 05:42:12", last_sign_in_at: "2015-12-17 06:05:44", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserOne", avatar_file_name: "avatar_1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 74539, avatar_updated_at: "2015-12-17 06:06:07", bio: "I'm user one!", title: "Software Engineer", type: nil, organization_id: 1},
  {email: "user2@gmail.com", first_name: "User", last_name: "Two", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-12-17 05:15:36", last_sign_in_at: "2015-12-11 23:20:48", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserTwo", avatar_file_name: "avatar_2.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 435374, avatar_updated_at: "2015-12-17 05:15:53", bio: nil, title: "Software Engineer", type: nil, organization_id: 1},
  {email: "user3@gmail.com", first_name: "User", last_name: "Three", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-12-17 05:16:04", last_sign_in_at: "2015-12-10 05:58:05", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserThree", avatar_file_name: "avatar_3.jpeg", avatar_content_type: "image/jpeg", avatar_file_size: 9967, avatar_updated_at: "2015-12-17 05:16:15", bio: nil, title: "Software Engineer", type: nil, organization_id: 1}
])
Manager.create!([
  {email: "manager@gmail.com", first_name: "Captain", last_name: "Manager", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 12, current_sign_in_at: "2016-03-19 01:16:13", last_sign_in_at: "2016-03-18 17:32:38", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@CaptainManager", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I'm managing all these homies", title: nil, type: "Manager", organization_id: 1}
])
Admin.create!([
  {email: "admin@gmail.com", first_name: "Admin", last_name: "Man", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 10, current_sign_in_at: "2016-03-18 21:07:49", last_sign_in_at: "2016-03-18 05:44:18", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@AdminMan", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I am the all ruling overlord!", title: nil, type: "Admin", organization_id: 1}
])