User.create!([
  {email: "matt@gmail.com", first_name: "Matthew", last_name: "Dick", encrypted_password: "$2a$10$SES/ldCEKBDGxXDejBG/WOfvAFsk3IAvRaekAC8oT85CYvZ9mCfMG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 37, current_sign_in_at: "2016-02-25 04:50:33", last_sign_in_at: "2016-02-17 16:01:17", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@MatthewDick", avatar_file_name: "my_avatar.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 291331, avatar_updated_at: "2015-12-18 06:27:10", bio: "Badass programmer, all day every day ;)", title: "Software Engineer", type: nil, organization_id: nil},
  {email: "tony@gmail.com", first_name: "Tony", last_name: "Decino", encrypted_password: "$2a$10$oZf50Ie8TchYLOWAwytVt.1S7gWm14wqR02HXQ.fnRStylQpUCFSS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2016-01-31 01:51:15", last_sign_in_at: "2016-01-20 13:56:59", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@TonyDecino", avatar_file_name: "tony_avatar.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 105745, avatar_updated_at: "2015-12-17 05:13:52", bio: nil, title: "Software Engineer", type: nil, organization_id: nil},
  {email: "user1@gmail.com", first_name: "User", last_name: "One", encrypted_password: "$2a$10$ccAG2T64yFzahN/3DbGXTOJy0m9cKxcoUBY6FGYhBbrjfKNCJOnZi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2015-12-17 06:05:44", last_sign_in_at: "2015-12-17 05:15:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserOne", avatar_file_name: "avatar_1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 74539, avatar_updated_at: "2015-12-17 06:06:07", bio: nil, title: "Software Engineer", type: nil, organization_id: nil},
  {email: "user2@gmail.com", first_name: "User", last_name: "Two", encrypted_password: "$2a$10$m1cmgW1cFzru.RnENRpTq.Z2dkqg6c5AuJbcVcS3l.F1xOGlzYRk6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2015-12-17 05:15:36", last_sign_in_at: "2015-12-11 23:20:48", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserTwo", avatar_file_name: "avatar_2.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 435374, avatar_updated_at: "2015-12-17 05:15:53", bio: nil, title: "Software Engineer", type: nil, organization_id: nil},
  {email: "user3@gmail.com", first_name: "User", last_name: "Three", encrypted_password: "$2a$10$lyFwk/xDQb9icf4XK3NAGu9cmh8BRdWOuebvKGszMSYW.fmbbS1P2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2015-12-17 05:16:04", last_sign_in_at: "2015-12-10 05:58:05", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@UserThree", avatar_file_name: "avatar_3.jpeg", avatar_content_type: "image/jpeg", avatar_file_size: 9967, avatar_updated_at: "2015-12-17 05:16:15", bio: nil, title: "Software Engineer", type: nil, organization_id: nil},
  {email: "manager@gmail.com", first_name: "Captain", last_name: "Manager", encrypted_password: "$2a$10$ySzEwvXn5yKskBGeSKRhJeoxwHPyyJZ77m7wNwaZhxnTcT1w8e3hS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-02-18 14:44:20", last_sign_in_at: "2016-02-15 19:18:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@CaptainManager", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I'm managing all these homies", title: nil, type: "Manager", organization_id: nil},
  {email: "admin@gmail.com", first_name: "Admin", last_name: "Man", encrypted_password: "$2a$10$H.km77uMUBsWxYo/fvoQa.xEPrns3IXDqUdOmeSD/5zXc/uT1n0y6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-02-26 15:10:31", last_sign_in_at: "2016-02-26 15:07:08", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@AdminMan", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I am the all ruling overlord!", title: nil, type: "Admin", organization_id: nil}
])
Comment.create!([
  {content: "I'm leaving this comment cause i feel passionate about this feedback", user_id: 5, feedback_id: 1},
  {content: "And I think you're doing a great job", user_id: 1, feedback_id: 5},
  {content: "Commenting on my own, recieved feedback", user_id: 1, feedback_id: 2},
  {content: "User1 has a comment as well", user_id: 3, feedback_id: 5},
  {content: "Thanks dude!", user_id: 2, feedback_id: 6},
  {content: "what?", user_id: 2, feedback_id: 6},
  {content: "Correct number of peers?", user_id: 2, feedback_id: 5},
  {content: "why are there 8?", user_id: 2, feedback_id: 5},
  {content: "but what about here?", user_id: 2, feedback_id: 9},
  {content: "Hey", user_id: 1, feedback_id: 10},
  {content: "sup with comments?", user_id: 1, feedback_id: 17},
  {content: "now?", user_id: 1, feedback_id: 17},
  {content: "comment peer count test", user_id: 1, feedback_id: 17},
  {content: "first comment", user_id: 1, feedback_id: 18},
  {content: "second comment", user_id: 1, feedback_id: 18},
  {content: "another comment", user_id: 1, feedback_id: 18},
  {content: "and another", user_id: 1, feedback_id: 18},
  {content: "no peers?", user_id: 1, feedback_id: 18},
  {content: "wtf..", user_id: 1, feedback_id: 18},
  {content: "well?", user_id: 1, feedback_id: 16},
  {content: "wtf...", user_id: 1, feedback_id: 16},
  {content: "sup", user_id: 1, feedback_id: 16},
  {content: "again", user_id: 1, feedback_id: 16},
  {content: "working?", user_id: 1, feedback_id: 19},
  {content: "nope", user_id: 1, feedback_id: 19},
  {content: "now it's working????", user_id: 1, feedback_id: 19},
  {content: "Yea you need to do better", user_id: 2, feedback_id: 9},
  {content: "great job #leadership", user_id: 1, feedback_id: 16},
  {content: "and also #bravery", user_id: 1, feedback_id: 16},
  {content: "i'm a baller #leadership", user_id: 1, feedback_id: 10},
  {content: "what are you looking at? #punk", user_id: 1, feedback_id: 10},
  {content: "or try this on: #bravery", user_id: 1, feedback_id: 10},
  {content: "#stopsucking", user_id: 1, feedback_id: 20},
  {content: "does it?", user_id: 1, feedback_id: 21},
  {content: "does it??", user_id: 1, feedback_id: 21},
  {content: "comment", user_id: 1, feedback_id: 22},
  {content: "with comment", user_id: 1, feedback_id: 23},
  {content: "hey", user_id: 1, feedback_id: 24},
  {content: "doesn't submit though, right?\r\n\r\nwe will see.", user_id: 1, feedback_id: 24},
  {content: "but then what?\r\nare we going to keep running with this until the end of time?\r\n\r\ni don't like it", user_id: 1, feedback_id: 24},
  {content: "am i that brave? #flattered", user_id: 1, feedback_id: 10},
  {content: "this will be ugly #sodamnuglyithurts", user_id: 1, feedback_id: 25},
  {content: "much better", user_id: 1, feedback_id: 26},
  {content: "sup wit it?", user_id: 1, feedback_id: 25},
  {content: "hey", user_id: 2, feedback_id: 20},
  {content: "it's", user_id: 2, feedback_id: 20},
  {content: "me!", user_id: 2, feedback_id: 20},
  {content: "tony!", user_id: 2, feedback_id: 20},
  {content: "work for me", user_id: 1, feedback_id: 26},
  {content: "Thanks you guise..", user_id: 1, feedback_id: 19},
  {content: "huh?\r\n", user_id: 1, feedback_id: 15},
  {content: "yuuuup", user_id: 1, feedback_id: 33},
  {content: "with comment", user_id: 1, feedback_id: 34},
  {content: "hey", user_id: 1, feedback_id: 35},
  {content: "what?", user_id: 1, feedback_id: 36}
])
CommentLink.create!([
  {comment_id: 2, user_id: 3, agree: nil},
  {comment_id: 2, user_id: 4, agree: nil},
  {comment_id: 2, user_id: 5, agree: nil},
  {comment_id: 3, user_id: 2, agree: nil},
  {comment_id: 3, user_id: 3, agree: true},
  {comment_id: 3, user_id: 4, agree: nil},
  {comment_id: 3, user_id: 5, agree: nil},
  {comment_id: 4, user_id: 1, agree: nil},
  {comment_id: 4, user_id: 4, agree: nil},
  {comment_id: 4, user_id: 5, agree: nil},
  {comment_id: 5, user_id: 3, agree: nil},
  {comment_id: 5, user_id: 4, agree: nil},
  {comment_id: 5, user_id: 5, agree: nil},
  {comment_id: 6, user_id: 3, agree: nil},
  {comment_id: 6, user_id: 4, agree: nil},
  {comment_id: 6, user_id: 5, agree: nil},
  {comment_id: 7, user_id: 3, agree: nil},
  {comment_id: 7, user_id: 4, agree: nil},
  {comment_id: 7, user_id: 5, agree: nil},
  {comment_id: 8, user_id: 3, agree: nil},
  {comment_id: 8, user_id: 4, agree: nil},
  {comment_id: 8, user_id: 5, agree: nil},
  {comment_id: 9, user_id: 3, agree: nil},
  {comment_id: 9, user_id: 4, agree: nil},
  {comment_id: 9, user_id: 5, agree: nil},
  {comment_id: 10, user_id: 3, agree: nil},
  {comment_id: 10, user_id: 4, agree: nil},
  {comment_id: 10, user_id: 5, agree: nil},
  {comment_id: 11, user_id: 3, agree: nil},
  {comment_id: 11, user_id: 4, agree: nil},
  {comment_id: 11, user_id: 5, agree: nil},
  {comment_id: 12, user_id: 3, agree: nil},
  {comment_id: 12, user_id: 4, agree: nil},
  {comment_id: 12, user_id: 5, agree: nil},
  {comment_id: 13, user_id: 3, agree: nil},
  {comment_id: 13, user_id: 4, agree: nil},
  {comment_id: 13, user_id: 5, agree: nil},
  {comment_id: 14, user_id: 3, agree: nil},
  {comment_id: 14, user_id: 4, agree: nil},
  {comment_id: 14, user_id: 5, agree: nil},
  {comment_id: 15, user_id: 3, agree: nil},
  {comment_id: 15, user_id: 4, agree: nil},
  {comment_id: 15, user_id: 5, agree: nil},
  {comment_id: 16, user_id: 3, agree: nil},
  {comment_id: 16, user_id: 4, agree: nil},
  {comment_id: 16, user_id: 5, agree: nil},
  {comment_id: 17, user_id: 3, agree: nil},
  {comment_id: 17, user_id: 4, agree: nil},
  {comment_id: 17, user_id: 5, agree: nil},
  {comment_id: 18, user_id: 3, agree: nil},
  {comment_id: 18, user_id: 4, agree: nil},
  {comment_id: 18, user_id: 5, agree: nil},
  {comment_id: 19, user_id: 3, agree: nil},
  {comment_id: 19, user_id: 4, agree: nil},
  {comment_id: 19, user_id: 5, agree: nil},
  {comment_id: 20, user_id: 3, agree: nil},
  {comment_id: 20, user_id: 4, agree: nil},
  {comment_id: 20, user_id: 5, agree: nil},
  {comment_id: 21, user_id: 3, agree: nil},
  {comment_id: 21, user_id: 4, agree: nil},
  {comment_id: 21, user_id: 5, agree: nil},
  {comment_id: 22, user_id: 3, agree: nil},
  {comment_id: 22, user_id: 4, agree: nil},
  {comment_id: 22, user_id: 5, agree: nil},
  {comment_id: 23, user_id: 3, agree: nil},
  {comment_id: 23, user_id: 4, agree: nil},
  {comment_id: 23, user_id: 5, agree: nil},
  {comment_id: 24, user_id: 3, agree: nil},
  {comment_id: 24, user_id: 4, agree: nil},
  {comment_id: 24, user_id: 5, agree: nil},
  {comment_id: 5, user_id: 1, agree: nil},
  {comment_id: 6, user_id: 1, agree: nil},
  {comment_id: 7, user_id: 1, agree: nil},
  {comment_id: 7, user_id: 3, agree: nil},
  {comment_id: 7, user_id: 4, agree: nil},
  {comment_id: 7, user_id: 5, agree: nil},
  {comment_id: 8, user_id: 1, agree: nil},
  {comment_id: 8, user_id: 3, agree: nil},
  {comment_id: 8, user_id: 4, agree: nil},
  {comment_id: 8, user_id: 5, agree: nil},
  {comment_id: 9, user_id: 1, agree: nil},
  {comment_id: 9, user_id: 4, agree: nil},
  {comment_id: 10, user_id: 2, agree: nil},
  {comment_id: 10, user_id: 3, agree: nil},
  {comment_id: 10, user_id: 5, agree: nil},
  {comment_id: 11, user_id: 3, agree: nil},
  {comment_id: 11, user_id: 5, agree: nil},
  {comment_id: 12, user_id: 3, agree: nil},
  {comment_id: 12, user_id: 5, agree: nil},
  {comment_id: 13, user_id: 3, agree: nil},
  {comment_id: 13, user_id: 5, agree: nil},
  {comment_id: 14, user_id: 4, agree: nil},
  {comment_id: 15, user_id: 4, agree: nil},
  {comment_id: 16, user_id: 4, agree: nil},
  {comment_id: 17, user_id: 4, agree: nil},
  {comment_id: 19, user_id: 4, agree: nil},
  {comment_id: 20, user_id: 2, agree: nil},
  {comment_id: 21, user_id: 2, agree: nil},
  {comment_id: 22, user_id: 2, agree: nil},
  {comment_id: 23, user_id: 2, agree: nil},
  {comment_id: 24, user_id: 3, agree: nil},
  {comment_id: 25, user_id: 3, agree: nil},
  {comment_id: 26, user_id: 3, agree: nil},
  {comment_id: 27, user_id: 4, agree: nil},
  {comment_id: 27, user_id: 1, agree: nil},
  {comment_id: 28, user_id: 2, agree: nil},
  {comment_id: 29, user_id: 2, agree: nil},
  {comment_id: 30, user_id: 3, agree: nil},
  {comment_id: 30, user_id: 5, agree: nil},
  {comment_id: 30, user_id: 2, agree: nil},
  {comment_id: 31, user_id: 3, agree: nil},
  {comment_id: 31, user_id: 5, agree: nil},
  {comment_id: 31, user_id: 2, agree: nil},
  {comment_id: 32, user_id: 3, agree: nil},
  {comment_id: 32, user_id: 5, agree: nil},
  {comment_id: 32, user_id: 2, agree: nil},
  {comment_id: 33, user_id: 3, agree: nil},
  {comment_id: 33, user_id: 4, agree: nil},
  {comment_id: 34, user_id: 2, agree: nil},
  {comment_id: 35, user_id: 2, agree: nil},
  {comment_id: 36, user_id: 5, agree: nil},
  {comment_id: 37, user_id: 2, agree: nil},
  {comment_id: 37, user_id: 4, agree: nil},
  {comment_id: 38, user_id: 2, agree: nil},
  {comment_id: 39, user_id: 2, agree: nil},
  {comment_id: 40, user_id: 2, agree: nil},
  {comment_id: 41, user_id: 3, agree: nil},
  {comment_id: 41, user_id: 5, agree: nil},
  {comment_id: 41, user_id: 2, agree: nil},
  {comment_id: 42, user_id: 3, agree: nil},
  {comment_id: 42, user_id: 4, agree: nil},
  {comment_id: 43, user_id: 2, agree: nil},
  {comment_id: 44, user_id: 3, agree: nil},
  {comment_id: 44, user_id: 4, agree: nil},
  {comment_id: 45, user_id: 3, agree: nil},
  {comment_id: 45, user_id: 4, agree: nil},
  {comment_id: 45, user_id: 1, agree: nil},
  {comment_id: 46, user_id: 3, agree: nil},
  {comment_id: 46, user_id: 4, agree: nil},
  {comment_id: 46, user_id: 1, agree: nil},
  {comment_id: 47, user_id: 3, agree: nil},
  {comment_id: 47, user_id: 4, agree: nil},
  {comment_id: 47, user_id: 1, agree: nil},
  {comment_id: 48, user_id: 3, agree: nil},
  {comment_id: 48, user_id: 4, agree: nil},
  {comment_id: 48, user_id: 1, agree: nil},
  {comment_id: 49, user_id: 2, agree: nil},
  {comment_id: 50, user_id: 3, agree: nil},
  {comment_id: 51, user_id: 5, agree: nil},
  {comment_id: 52, user_id: 3, agree: nil},
  {comment_id: 52, user_id: 5, agree: nil},
  {comment_id: 53, user_id: 3, agree: nil},
  {comment_id: 53, user_id: 4, agree: nil},
  {comment_id: 54, user_id: 3, agree: nil},
  {comment_id: 54, user_id: 2, agree: nil},
  {comment_id: 54, user_id: 2, agree: nil},
  {comment_id: 55, user_id: 3, agree: nil}
])
Feedback.create!([
  {user_id: 1, author_id: 2, content: "This is the first feedback in the system! Way to go!!", resonance_value: 1},
  {user_id: 1, author_id: 2, content: "Lets see what it looks like with peers", resonance_value: 0},
  {user_id: 2, author_id: 3, content: "LOOK AT ME NOW!", resonance_value: 1},
  {user_id: 2, author_id: 4, content: "Get on to the machine, bro!", resonance_value: 2},
  {user_id: 2, author_id: 1, content: "It's coming together man!", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "Hey I like your style", resonance_value: 1},
  {user_id: 4, author_id: 1, content: "User two, try to do something useful", resonance_value: 1},
  {user_id: 5, author_id: 1, content: "Hey there user 3", resonance_value: 1},
  {user_id: 5, author_id: 1, content: "Try it again then!", resonance_value: 1},
  {user_id: 1, author_id: 2, content: "It works on an enter..?", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "Yea man, I don't understand quite yet :(", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "Can I comment on a new feedback?", resonance_value: 1},
  {user_id: 2, author_id: 1, content: "How about now?", resonance_value: 1},
  {user_id: 5, author_id: 1, content: "And now?", resonance_value: 1},
  {user_id: 2, author_id: 1, content: "test", resonance_value: 1},
  {user_id: 1, author_id: 1, content: "Good it didn't work", resonance_value: -1},
  {user_id: 4, author_id: 1, content: "We are getting somewhere!", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "Lets test some comment scoring", resonance_value: 1},
  {user_id: 2, author_id: 1, content: "new comment logic", resonance_value: 1},
  {user_id: 2, author_id: 1, content: "You really sucked it up at the meeting today", resonance_value: 0},
  {user_id: 1, author_id: 1, content: "sup sup!", resonance_value: -1},
  {user_id: 1, author_id: 1, content: "lets leave a feedback, eh?", resonance_value: -1},
  {user_id: 1, author_id: 1, content: "new feedback", resonance_value: -1},
  {user_id: 1, author_id: 1, content: "do i need that role?", resonance_value: -1},
  {user_id: 1, author_id: 1, content: "Some long winded feedback.\r\nWith a space right here.\r\n\r\nAnd 2 spaces here.\r\n\r\n\r\nAnd at 3? That's all i have to say about that", resonance_value: -1},
  {user_id: 1, author_id: 1, content: "trial run, eh?", resonance_value: -1},
  {user_id: 2, author_id: 1, content: "just testing that I can only add unassigned peers", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "testing the peers things again...", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "adding everyone to this one..", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "again?", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "I can't understand why they won't add in. DEBUG!", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "what the hell man!", resonance_value: nil},
  {user_id: 2, author_id: 1, content: "i think i got it this time", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "testing share updating", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "sup", resonance_value: 0},
  {user_id: 2, author_id: 1, content: "you suck", resonance_value: 0}
])
FeedbackLink.create!([
  {feedback_id: nil, user_id: 3, agree: nil},
  {feedback_id: nil, user_id: 4, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 3, agree: nil},
  {feedback_id: nil, user_id: 4, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: 2, user_id: 3, agree: nil},
  {feedback_id: 2, user_id: 4, agree: nil},
  {feedback_id: 2, user_id: 5, agree: nil},
  {feedback_id: 3, user_id: 4, agree: nil},
  {feedback_id: 4, user_id: 1, agree: true},
  {feedback_id: 5, user_id: 3, agree: nil},
  {feedback_id: 5, user_id: 4, agree: nil},
  {feedback_id: 5, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: nil, agree: nil},
  {feedback_id: nil, user_id: nil, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: 9, user_id: 2, agree: true},
  {feedback_id: 9, user_id: 4, agree: nil},
  {feedback_id: 10, user_id: 3, agree: nil},
  {feedback_id: 10, user_id: 5, agree: nil},
  {feedback_id: 11, user_id: 3, agree: nil},
  {feedback_id: 11, user_id: 4, agree: nil},
  {feedback_id: 12, user_id: 3, agree: nil},
  {feedback_id: 13, user_id: 5, agree: nil},
  {feedback_id: 14, user_id: 5, agree: nil},
  {feedback_id: 15, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: 16, user_id: 2, agree: nil},
  {feedback_id: 17, user_id: 3, agree: nil},
  {feedback_id: 17, user_id: 5, agree: nil},
  {feedback_id: 18, user_id: 4, agree: nil},
  {feedback_id: 19, user_id: 3, agree: nil},
  {feedback_id: 20, user_id: 3, agree: nil},
  {feedback_id: 20, user_id: 4, agree: nil},
  {feedback_id: 21, user_id: 2, agree: nil},
  {feedback_id: 22, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: 23, user_id: 2, agree: nil},
  {feedback_id: 23, user_id: 4, agree: nil},
  {feedback_id: 24, user_id: 2, agree: nil},
  {feedback_id: 25, user_id: 3, agree: nil},
  {feedback_id: 25, user_id: 4, agree: nil},
  {feedback_id: 26, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: nil, user_id: 3, agree: nil},
  {feedback_id: nil, user_id: 3, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 3, agree: nil},
  {feedback_id: nil, user_id: 5, agree: nil},
  {feedback_id: nil, user_id: 2, agree: nil},
  {feedback_id: 26, user_id: 2, agree: nil},
  {feedback_id: 26, user_id: 2, agree: nil},
  {feedback_id: 26, user_id: 2, agree: nil},
  {feedback_id: 33, user_id: 3, agree: nil},
  {feedback_id: 33, user_id: 5, agree: nil},
  {feedback_id: 33, user_id: 4, agree: nil},
  {feedback_id: 34, user_id: 3, agree: nil},
  {feedback_id: 34, user_id: 4, agree: nil},
  {feedback_id: 34, user_id: 5, agree: nil},
  {feedback_id: 35, user_id: 3, agree: nil},
  {feedback_id: 35, user_id: 4, agree: nil},
  {feedback_id: 35, user_id: 5, agree: nil},
  {feedback_id: 36, user_id: 3, agree: nil}
])
ManagerEmployee.create!([
  {employee_id: 4, manager_id: 6},
  {employee_id: 5, manager_id: 6}
])
Tag.create!([
  {name: "#leadership"},
  {name: "#bravery"},
  {name: "#punk"},
  {name: "#stopsucking"},
  {name: "#flattered"},
  {name: "#sodamnuglyithurts"}
])
TagLink.create!([
  {tag_id: 1, feedback_id: 16},
  {tag_id: 2, feedback_id: 16},
  {tag_id: 1, feedback_id: 10},
  {tag_id: 3, feedback_id: 10},
  {tag_id: 2, feedback_id: 10},
  {tag_id: 4, feedback_id: 20},
  {tag_id: 5, feedback_id: 10},
  {tag_id: 6, feedback_id: 25}
])
Admin.create!([
  {email: "admin@gmail.com", first_name: "Admin", last_name: "Man", encrypted_password: "$2a$10$H.km77uMUBsWxYo/fvoQa.xEPrns3IXDqUdOmeSD/5zXc/uT1n0y6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-02-26 15:10:31", last_sign_in_at: "2016-02-26 15:07:08", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@AdminMan", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I am the all ruling overlord!", title: nil, type: "Admin", organization_id: nil}
])
Manager.create!([
  {email: "manager@gmail.com", first_name: "Captain", last_name: "Manager", encrypted_password: "$2a$10$ySzEwvXn5yKskBGeSKRhJeoxwHPyyJZ77m7wNwaZhxnTcT1w8e3hS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-02-18 14:44:20", last_sign_in_at: "2016-02-15 19:18:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", user_tag: "@CaptainManager", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, bio: "I'm managing all these homies", title: nil, type: "Manager", organization_id: nil}
])
